package ru.vsk.dr.osago_demo_sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Driver implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Дата рождения")
	private java.util.Date birthDate;
	@org.kie.api.definition.type.Label("дата выдачи прав")
	private java.util.Date stageFromDate;
	@org.kie.api.definition.type.Label("возраст")
	private int age;
	@org.kie.api.definition.type.Label("стаж")
	private int stage;

	@org.kie.api.definition.type.Label("Предыдущий КБМ")
	private java.lang.String kbmPrevious;

	@org.kie.api.definition.type.Label(value = "\u041A\u043E\u043B-\u0432\u043E \u0441\u0442\u0440\u0430\u0445\u043E\u0432\u044B\u0445 \u0432\u043E\u0437\u043C\u0435\u0449\u0435\u043D\u0438\u0439")
	private int claimCount;

	@org.kie.api.definition.type.Label(value = "\u041D\u043E\u0432\u044B\u0439 \u041A\u0411\u041C")
	private java.lang.String kbmNew;

	public Driver() {
	}

	public java.util.Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(java.util.Date birthDate) {
		this.birthDate = birthDate;
	}

	public java.util.Date getStageFromDate() {
		return this.stageFromDate;
	}

	public void setStageFromDate(java.util.Date stageFromDate) {
		this.stageFromDate = stageFromDate;
	}

	public java.lang.String getKbmPrevious() {
		return this.kbmPrevious;
	}

	public void setKbmPrevious(java.lang.String kbmPrevious) {
		this.kbmPrevious = kbmPrevious;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public int getStage() {
		return this.stage;
	}

	public void setStage(int stage) {
		this.stage = stage;
	}

	public int getClaimCount() {
		return this.claimCount;
	}

	public void setClaimCount(int claimCount) {
		this.claimCount = claimCount;
	}

	public java.lang.String getKbmNew() {
		return this.kbmNew;
	}

	public void setKbmNew(java.lang.String kbmNew) {
		this.kbmNew = kbmNew;
	}

	public Driver(java.util.Date birthDate, java.util.Date stageFromDate,
			int age, int stage, java.lang.String kbmPrevious, int claimCount,
			java.lang.String kbmNew) {
		this.birthDate = birthDate;
		this.stageFromDate = stageFromDate;
		this.age = age;
		this.stage = stage;
		this.kbmPrevious = kbmPrevious;
		this.claimCount = claimCount;
		this.kbmNew = kbmNew;
	}
	
	public java.lang.String toString(){
	    return "Driver("+
	    "birthDate='"+ birthDate+"' "+
		"stageFromDate='"+ stageFromDate+"' "+
		"age='"+ age+"' "+
		"stage='"+ stage+"' "+
		"kbmPrevious='"+ kbmPrevious+"' "+
		"claimCount='"+ claimCount+"' "+
		"kbmNew='"+ kbmNew+"')";
	}

}