package ru.vsk.dr.osago_demo_sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Insurant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "\u0442\u0438\u043F \u043B\u0438\u0446\u0430")
	private java.lang.String type;

	public Insurant() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public Insurant(java.lang.String type) {
		this.type = type;
	}
	
	public java.lang.String toString(){
	    return "Insurant(type='"+type+"')";
	}

}