package ru.vsk.dr.osago_demo_sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Koefficient implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String code;
	private java.lang.String name;
	private double value;

	public Koefficient() {
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	public Koefficient(java.lang.String code, java.lang.String name,
			double value) {
		this.code = code;
		this.name = name;
		this.value = value;
	}

}