package ru.vsk.dr.osago_demo_sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UsingTerritory implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String region;
	private java.lang.String city;

	private double koefForAuto;

	private double koefForTractor;

	public UsingTerritory() {
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public double getKoefForAuto() {
		return this.koefForAuto;
	}

	public void setKoefForAuto(double koefForAuto) {
		this.koefForAuto = koefForAuto;
	}

	public double getKoefForTractor() {
		return this.koefForTractor;
	}

	public void setKoefForTractor(double koefForTractor) {
		this.koefForTractor = koefForTractor;
	}

	public UsingTerritory(java.lang.String region, java.lang.String city,
			double koefForAuto, double koefForTractor) {
		this.region = region;
		this.city = city;
		this.koefForAuto = koefForAuto;
		this.koefForTractor = koefForTractor;
	}
	
	public java.lang.String toString(){
	    return "UsingTerritory("+
    	    "region='"        +region        +"' "+
    		"city='"          +city          +"' "+
    		"koefForAuto='"   +koefForAuto   +"' "+
    		"koefForTractor='"+koefForTractor+"')";
	}
}